# Generated by Django 3.2.25 on 2025-04-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='organization',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organizations',
            field=models.ManyToManyField(blank=True, related_name='members', to='crm.Organization', verbose_name='Organizacje'),
        ),
    ]
