# Generated by Django 5.2 on 2025-04-09 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='organization',
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organizacja', 'verbose_name_plural': 'Organizacje'},
        ),
        migrations.RemoveField(
            model_name='organization',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, verbose_name='Strona internetowa'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis problemu')),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('in_progress', 'W trakcie'), ('waiting', 'Oczekujące'), ('resolved', 'Rozwiązane'), ('closed', 'Zamknięte')], default='new', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki'), ('critical', 'Krytyczny')], default='medium', max_length=20, verbose_name='Priorytet')),
                ('category', models.CharField(choices=[('hardware', 'Sprzęt'), ('software', 'Oprogramowanie'), ('network', 'Sieć'), ('account', 'Konto'), ('other', 'Inne')], default='other', max_length=20, verbose_name='Kategoria')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Data rozwiązania')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data zamknięcia')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Przypisany do')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Utworzony przez')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='crm.organization', verbose_name='Organizacja')),
            ],
            options={
                'verbose_name': 'Zgłoszenie',
                'verbose_name_plural': 'Zgłoszenia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Logowanie'), ('logout', 'Wylogowanie'), ('ticket_created', 'Utworzenie zgłoszenia'), ('ticket_updated', 'Aktualizacja zgłoszenia'), ('ticket_commented', 'Komentarz do zgłoszenia'), ('ticket_resolved', 'Rozwiązanie zgłoszenia'), ('ticket_closed', 'Zamknięcie zgłoszenia'), ('ticket_reopened', 'Ponowne otwarcie zgłoszenia')], max_length=30, verbose_name='Typ akcji')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adres IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='crm.ticket', verbose_name='Zgłoszenie')),
            ],
            options={
                'verbose_name': 'Log aktywności',
                'verbose_name_plural': 'Logi aktywności',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/', verbose_name='Plik')),
                ('filename', models.CharField(max_length=255, verbose_name='Nazwa pliku')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.ticket', verbose_name='Zgłoszenie')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Dodany przez')),
            ],
            options={
                'verbose_name': 'Załącznik do zgłoszenia',
                'verbose_name_plural': 'Załączniki do zgłoszeń',
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Treść')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.ticket', verbose_name='Zgłoszenie')),
            ],
            options={
                'verbose_name': 'Komentarz do zgłoszenia',
                'verbose_name_plural': 'Komentarze do zgłoszeń',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('moderator', 'Moderator'), ('client', 'Klient')], default='client', max_length=20, verbose_name='Rola')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='crm.organization', verbose_name='Organizacja')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil użytkownika',
                'verbose_name_plural': 'Profile użytkowników',
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
    ]
