# Generated by Django 3.2.25 on 2025-04-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20250418_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketattachment',
            name='accepted_policy',
            field=models.BooleanField(default=False, verbose_name='Zaakceptowano regulamin'),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='encryption_key',
            field=models.BinaryField(blank=True, null=True, verbose_name='Klucz szyfrowania'),
        ),
    ]
