# Generated by Django 3.2.25 on 2025-05-27 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_allow_null_user_in_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, verbose_name='Nieudane próby logowania'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='Konto zablokowane'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data blokady'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Zalogowanie'), ('logout', 'Wylogowanie'), ('login_failed', 'Nieudane logowanie'), ('account_locked', 'Blokada konta'), ('account_unlocked', 'Odblokowanie konta'), ('ticket_created', 'Utworzenie'), ('ticket_updated', 'Aktualizacja'), ('ticket_commented', 'Komentarz'), ('ticket_resolved', 'Rozwiązanie'), ('ticket_closed', 'Zamknięcie'), ('ticket_reopened', 'Wznowienie'), ('preferences_updated', 'Aktualizacja preferencji'), ('password_changed', 'Zmiana hasła'), ('404_error', 'Błąd 404 - Strona nie znaleziona'), ('403_error', 'Błąd 403 - Brak dostępu'), ('ticket_attachment_added', 'Dodano załącznik')], max_length=30, verbose_name='Typ akcji'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Wprowadź poprawny numer telefonu. Format: '+48 123 456 789' lub '123456789'.", regex='^(?:\\+?48)?[ -]?(?:\\d{3}[ -]?\\d{3}[ -]?\\d{3}|\\d{9})$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Wprowadź poprawny numer telefonu. Format: '+48 123 456 789' lub '123456789'.", regex='^(?:\\+?48)?[ -]?(?:\\d{3}[ -]?\\d{3}[ -]?\\d{3}|\\d{9})$')], verbose_name='Telefon'),
        ),
    ]
